### 주문 생성
POST http://localhost:8080/v1/orders
Content-Type: application/json

{
  "customerId": 1,
  "orderItems": [
    {
      "productId": "1744805698482_56d7eaa4-00e2-4586-8af5-a5b8911111c0",
      "quantity": 2
    }
  ],
  "paymentMethod": "CREDIT_CARD"
}

### 주문 생성
POST http://localhost:8080/v1/orders
Content-Type: application/json

{
  "customerId": 1,
  "orderItems": [
    {
      "productId": "1744805698500_e654912d-c885-4f04-9f08-7279a2607193",
      "quantity": 2
    }
  ],
  "paymentMethod": "CREDIT_CARD"
}

### 결제 완료
POST http://localhost:8080/v1/orders/6/payment
Content-Type: application/json

{
  "success": true
}

### 결제 처리 실패
POST http://localhost:8080/v1/orders/6/payment
Content-Type: application/json

{
  "success": false
}

### 주문완료
POST http://localhost:8080/v1/orders/6/complete
Content-Type: application/x-www-form-urlencoded

### 주문취소
POST http://localhost:8080/v1/orders/5/cancel
Content-Type: application/x-www-form-urlencoded